# Generated by Django 2.2 on 2020-05-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=2)),
                ('date_of_birth', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(choices=[('PUR', 'PURNEA')], max_length=3)),
                ('state', models.CharField(choices=[('BR', 'BIHAR')], max_length=3)),
                ('education_qualification', models.CharField(max_length=200)),
                ('name_of_institute', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='students/dp/')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
