# Generated by Django 2.2 on 2020-05-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200521_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
