# Generated by Django 2.2 on 2020-05-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20200526_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('1', 'FULL'), ('2', 'Installment')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
