# Generated by Django 2.2 on 2020-05-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ManyToManyField(to='students.Payment'),
        ),
    ]
