# Generated by Django 2.2 on 2020-05-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20200527_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[('BR', 'BIHAR')], default='1', max_length=1),
        ),
    ]
