# Generated by Django 2.2 on 2020-06-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20200527_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.BooleanField(default='False'),
        ),
    ]
