# Generated by Django 2.2 on 2020-06-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20200605_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
