# Generated by Django 2.2 on 2020-06-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20200609_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_code',
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_txnid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
