# Generated by Django 2.2 on 2020-06-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_auto_20200609_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='txn_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
