# Generated by Django 2.2 on 2020-06-11 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_payment_txn_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
    ]
