# Generated by Django 2.2 on 2020-06-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_remove_student_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
